### ISSUE TITLE
Browerify issue

### ISSUE THREAD

**Issue by SlyryD** [dcodeIO/protobuf.js#1045]
protobuf.js version: master (6.8.7 candidate)

An error occurs when creating a browserify bundle that has protobufjs as a dependency. To repro, unzip [slyryd-test.zip](https://github.com/dcodeIO/protobuf.js/files/2018174/slyryd-test.zip), and run `npm install` and `npm run browserify`. Removing the following line in the protobuf.js package.json file fixes the issue:

`"browser": "dist/protobuf.js",`

Example error:
```
Error: Cannot find module '4' from 'C:\Users\slyryd\Test\slyryd-test\node_modules\protobufjs\dist'
    at C:\Users\slyryd\Test\slyryd-test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\slyryd\Test\slyryd-test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\slyryd\Test\slyryd-test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\slyryd\Test\slyryd-test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\slyryd\Test\slyryd-test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\slyryd\Test\slyryd-test\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
```

**Comment by SlyryD** [comment]
According to the browser spec, the entry point should be specified, rather than the bundle file.
https://github.com/defunctzombie/package-browser-field-spec

Removing the line will make it look at index.js by default. If you wanted, there might also be some more complex logic you could use to specify src/index.js, src/index-light.js, and src/index-minimal.js.

**Comment by SlyryD** [comment]
I opened a pull request for this: https://github.com/dcodeIO/protobuf.js/pull/1046/

**Comment by SlyryD** [comment]
Resolved
