### ISSUE TITLE
Decoding tcp socket messages without delimiters

### ISSUE THREAD

**Issue by IsaDerosier** [dcodeIO/protobuf.js#1055]
protobuf.js version: ^6.8.6

I'm working with a ruby_protobuf server that responds to my protobuf.js client's protobuf message "ReadRequest" with a "RemotePIOMessage" containing measurement data etc. The communication protocol of the server is 1) ASCI length of the message + Newline, 2) protobuf message.
I'm buffering the incoming data on the tcp socket until I get a response that's as long as the intended length in 1), but 1/3 times the entire thing just crashes during the decodeDelimited with a ProtocolError.

```
socket.on('data', function(data) {
		if(responseLength == -1 && Number(data)){
			console.log(Number(data));
			responseLength = Number(data);
		}else{
			var totalLength = rBuf.length + data.length;
			rBuf = Buffer.concat([rBuf, data], totalLength);
			console.log(rBuf);
		}
		console.log(responseLength);
		if(responseLength>0 && rBuf.length >= responseLength){
			var response = REMOTE_PIO_MESSAGE.decodeDelimited(rBuf);
			console.log(response);
			rBuf = Buffer.alloc(0);
			responseLength = -1;
		}
	})
```

```
Stack trace:

  throw util.ProtocolError("missing required 'result'",{instance:m})
  ^
ProtocolError: missing required 'result'
    at Object.CustomError [as ProtocolError] (/home/pi/Desktop/piotest/node_modules/protobufjs/src/util/minimal.js:251:20)
    at Type.RemotePIOMessage$decode [as decode] (eval at Codegen (/home/pi/Desktop/piotest/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:61:14)
    at Type.decodeDelimited (/home/pi/Desktop/piotest/node_modules/protobufjs/src/type.js:520:17)
    at Socket.<anonymous> (/home/pi/Desktop/piotest/test.js:69:38)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)

```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
