### ISSUE TITLE
Unable to create static module for proto containing message called 'Object'

### ISSUE THREAD

**Issue by BryceCicada** [dcodeIO/protobuf.js#1058]
protobuf.js version: 6.8.6

Steps to reproduce:
- Create ```object.proto```
```proto
syntax = "proto3";
message Object {}
```
- Create `bundle.js` as a static-module:
```
npx pbjs -t static-module object.proto -o bundle.js
```
- Create `main.js`:
```js
require('./bundle.js').Object.create({});
```
- Run `main.js`
```
node main.js
```
Witness error
```
/path/to/project/bundle.js:37
                for (var keys = Object.keys(properties), i = 0; i < keys.length; ++i)
                                       ^

TypeError: Object.keys is not a function
    at new Object (/path/to/project/bundle.js:37:40)
    at Function.create (/path/to/project/bundle.js:51:20)
    at Object.<anonymous> (/path/to/project/main.js:1:93)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
```

Expected result is no error.

---

Clearly, the message `Object` causes a name conflict with the javascript `Object`.

It also fails if I create `bundle.js` as a json-module (`npx pbjs -t json-module object.proto -o bundle.js`) 

In the static-module case, it can be temporarily fixed in `bundle.js` by assigning javascript's `Object` to a variable `JSObject`, say, and using `JSObject.keys(properties)`.   However, this requires such a change each time the code is generated.

A better work-around is to use reflection.  For example, there is no error if `main.js` is:
```javascript
let protobuf = require('protobufjs');
let root = protobuf.loadSync('object.proto')
root.Object.create()
```

In my particular case, I don't have control of the proto file to change the message name.  

Using reflection is ok, but it's a shame.  Particularly because I'm using Typescript, for which I import the types from a generated `bundle.d.ts`, but then I need a `bundle.js` around at runtime (could just be empty).  It's a shame to have this unused file knocking around... I'd like it to be useful containing a static module.

I raise it as an issue here because:
  * The same proto works fine in other languages.
  * The inconsistency between using reflection vs. static code.

Thanks for any consideration.

**Comment by BryceCicada** [comment]
The code that generates a reference to 'Object' is at https://github.com/dcodeIO/protobuf.js/blob/462132f222d8febb8211d839635aad5b82dc6315/src/type.js#L207.

Would it make sense to replace Object.keys() with a "for .. in" loop (with check for hasOwnProperty()) there?  I guess it could either be done always, or just when mtype.name === 'Object'.

Any thoughts?

**Comment by BryceCicada** [comment]
Another workaround is to use `root.Object.fromObject({})`.  

This is works unless the Object message contains an enum definition.

**Comment by nejcgalof** [comment]
Will be any update about this issue and MR?
