### ISSUE TITLE
pbjs unable to find google.protobuf.Empty

### ISSUE THREAD

**Issue by gudmundur** [dcodeIO/protobuf.js#1061]
protobuf.js version: 6.8.6

While trying to generate code with `pbjs` it is unable to find the common `google.protobuf.Empty` proto. The `.proto` file contains a `import "google/protobuf/empty.proto";`. Running `pbjs` with `pbjs --wrap es6 -t static-module path_to_proto.proto` causes it to terminate with:

```
node_modules/protobufjs/cli/pbjs.js:235
            throw err;
            ^

Error: no such type: google.protobuf.Empty
    at Service.lookupType (node_modules/protobufjs/src/namespace.js:382:15)
    at Method.resolve (node_modules/protobufjs/src/method.js:147:44)
    at Service.resolveAll (node_modules/protobufjs/src/service.js:111:20)
    at Namespace.resolveAll (node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (node_modules/protobufjs/src/namespace.js:307:25)
    at Namespace.resolveAll (node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (node_modules/protobufjs/src/namespace.js:307:25)
    at Root.resolveAll (node_modules/protobufjs/src/root.js:246:43)
    at Object.main (node_modules/protobufjs/cli/pbjs.js:226:48)
```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
