### ISSUE TITLE
pbjs cli cannot parse nested brackets in the definition of FieldOptions

### ISSUE THREAD

**Issue by yuezhihan** [dcodeIO/protobuf.js#1094]
protobuf.js version: 6.8.8

pbjs cli cannot parse nested brackets in the definition of FieldOptions

such as

```js
message SetTabWisestarAlgoFeatureConfRequest {
    required dry.admincgi.AdminBase admin_base         = 1;
    required SetTabWisestarAlgoFeatureConfParam params = 2;

    message SetTabWisestarAlgoFeatureConfParam {
        required int32 algo_id                = 1;
        required int32 feature_db_id          = 2;
        required string feature_db_name       = 3;
        required string feature_primary_key   = 4;
        required string feature_secondary_key = 5;
        required int32 algo_access_data_mode  = 6 [(dry.pblint.rules).int32 = {in: [1, 2]}];
        required int32 ft_use_type            = 7 [(dry.pblint.rules).int32 = {in: [0, 1, 2]}];
    }
}
```

```
Error: illegal value '[' (data.proto, line 90)
    at illegal (C:\Users\zhihanyue\AppData\Roaming\npm\node_modules\protobufjs\src\parse.js:94:16)
    at readValue (C:\Users\zhihanyue\AppData\Roaming\npm\node_modules\protobufjs\src\parse.js:133:19)
    at parseOptionValue (C:\Users\zhihanyue\AppData\Roaming\npm\node_modules\protobufjs\src\parse.js:568:63)
    at parseOption (C:\Users\zhihanyue\AppData\Roaming\npm\node_modules\protobufjs\src\parse.js:551:9)
    at parseInlineOptions (C:\Users\zhihanyue\AppData\Roaming\npm\node_modules\protobufjs\src\parse.js:585:17)
    at parseField_line (C:\Users\zhihanyue\AppData\Roaming\npm\node_modules\protobufjs\src\parse.js:376:13)
    at ifBlock (C:\Users\zhihanyue\AppData\Roaming\npm\node_modules\protobufjs\src\parse.js:290:17)
    at parseField (C:\Users\zhihanyue\AppData\Roaming\npm\node_modules\protobufjs\src\parse.js:366:9)
    at parseType_block (C:\Users\zhihanyue\AppData\Roaming\npm\node_modules\protobufjs\src\parse.js:317:21)
    at ifBlock (C:\Users\zhihanyue\AppData\Roaming\npm\node_modules\protobufjs\src\parse.js:286:17)
```

**_[_** (dry.pblint.rules).int32 = {in: **_[_** 1, 2 **_]_** } **_]_**

When faced with the nested brackets: [ [ ] ], pbjs reports a syntax error.

The nested brackets syntax works in google.protobuf, and can be successfully compiled by protoc.

**Comment by zhaomoloco** [comment]
One solution is to change it to this format for the repeated option field:
[(dry.pblint.rules).int32 = {in: 1, in: 2}];

It should be handled properly

**Comment by adamgering** [comment]
What's the status of this issue? Ran into the same bug.

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
