### ISSUE TITLE
resolveAll() throws exception for messages referencing google.protobuf.empty

### ISSUE THREAD

**Issue by pdubroy** [dcodeIO/protobuf.js#1098]
protobuf.js version: 6.8.8

I was trying to follow the instructions from grpc.io on [setting up a Node.js GRPC client](https://grpc.io/docs/tutorials/basic/node.html), and am running into problems with one of my proto definitions that uses `google.protobuf.Empty`. I managed to narrow it down to the following repro case:

I created a file `repro.js` in the root of the repository, with the following contents:

```js
require('.').loadSync('./tests/data/common.proto').resolveAll();
```

Then, when I run it with `node repro.js`, I see the following error:

```
/Users/pdubroy/dev/third_party/protobuf.js/src/namespace.js:410
        throw Error("no such Type or Enum '" + path + "' in " + this);
        ^

Error: no such Type or Enum 'google.protobuf.empty' in Type .Something
    at Type.lookupTypeOrEnum (/Users/pdubroy/dev/third_party/protobuf.js/src/namespace.js:410:15)
    at Field.resolve (/Users/pdubroy/dev/third_party/protobuf.js/src/field.js:265:94)
    at Type.resolveAll (/Users/pdubroy/dev/third_party/protobuf.js/src/type.js:304:21)
    at Root.resolveAll (/Users/pdubroy/dev/third_party/protobuf.js/src/namespace.js:307:25)
    at Root.resolveAll (/Users/pdubroy/dev/third_party/protobuf.js/src/root.js:246:43)
    at Object.<anonymous> (/Users/pdubroy/dev/third_party/protobuf.js/repro.js:1:114)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

Possibly related to #1042 and #1061.

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
