### ISSUE TITLE
Encode map<string, string> throw error for null value

### ISSUE THREAD

**Issue by wdinau** [dcodeIO/protobuf.js#1195]
protobuf.js version: ~6.8.0

When protobuf defined with map<string, string>, but the actual JSON contains `null` value, error thrown. 
In the following instance, when protobuf the message below when `request` is defined as `map<string, string>` error occurs.

I'm aware of a fix of yours in 2017 around March April to stop similar error, checking length to null is not prevented inside map<string, string>.

```js
let stripeEvent = {
  "id": "evt_1ENTn3EswZoy3OfQLldOntuv",
  "request": {
    "id": "req_e9FishNtSluAA5",
    "idempotency_key": null,
    "xx": 1234
  },
  "type": "customer.subscription.created"
};
```

```
error: uncaughtException: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type object
    at Function.byteLength (buffer.js:514:11)
    at BufferWriter.write_string_buffer [as string] (/Users/sherrywang/Projects/payment-proxy/node_modules/protobufjs/src/writer_buffer.js:68:22)
    at Type.RawSubscriptionEvent$encode [as encode] (eval at Codegen (/Users/sherrywang/Projects/payment-proxy/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:19:15)

```

**Comment by zyf0330** [comment]
I meet this problem too.

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
