### ISSUE TITLE
Descriptors extension fails to take into account default values

### ISSUE THREAD

**Issue by jroper** [dcodeIO/protobuf.js#1196]
I get the following error using `fromDescriptor`:

```
TypeError: Cannot read property 'add' of undefined
    at Function.fromDescriptor (node_modules/protobufjs/ext/descriptor/index.js:219:66)
    at Function.fromDescriptor (node_modules/protobufjs/ext/descriptor/index.js:92:42)
```

Here's the code that throws the exception:

```javascript
            if (descriptor.field[i].hasOwnProperty("oneofIndex")) // eslint-disable-line no-prototype-builtins
                type.oneofsArray[descriptor.field[i].oneofIndex].add(field);
```

The reason it's throwing an exception is that the `oneofIndex` property is present, but is set to its default value (`0`) - ie, it is effectively unset, but the above code fails to take that into account.

I've tried setting `defaults: false` when loading the file, it doesn't seem to help. The problem may be that I'm importing the `descriptor.proto` into a `proto3` syntax file, and so default values are being forced because there's no such thing as unset in `proto3`? It seems like the above code should be updated anyway to handle this in future.

**Comment by jroper** [comment]
I found the reason why the defaults are there, I only get this when I've sent the message over gRPC, using the official node gRPC client, and it does a `toObject` that hard codes `defaults: true`:

https://github.com/grpc/grpc-node/blob/master/packages/grpc-native-core/src/protobuf_js_6_common.js#L41

**Comment by murgatroid99** [comment]
As a bit of an aside, I would suggest using `@grpc/proto-loader` to load your `.proto` files for use with the gRPC client. Among other things, that allows you to set any of the options as you want.

**Comment by jackkav** [comment]
I was getting this error too when working with `grpc-reflection-js` 
workaround is to force protobufjs to a newer version in package.json
```
"overrides":{"protobufjs":"7.1.2"}
```

**Comment by dcodeIO** [comment]
This comes from passing descriptors through `toObject(..., { defaults: true })`, which materializes an unset `oneofIndex` as `0` and loses the distinction from a real first oneof index. That looks like unintended usage rather than a bug in protobuf.js. Apart from that, the original gRPC path appears to be gone, and current `grpc-reflection-js` / `@grpc/proto-loader` descriptor loading preserves presence here by passing raw bytes or decoded descriptor messages to `Root.fromDescriptor`.

Hence closing this as no longer actionable.
