### ISSUE TITLE
ReferenceError: val is not defined

### ISSUE THREAD

**Issue by zscorpio** [dcodeIO/ProtoBuf.js#217]
node_modules/protobufjs/dist/ProtoBuf.js:2195
                            throw(e);
                                  ^
ReferenceError: val is not defined
    at module.exports.ByteBufferPrototype.readVString (/Users/scorpio/Sites/teamtalk-nodejs/node_modules/protobufjs/node_modules/bytebuffer/dist/ByteBufferNB.js:1999:67)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/scorpio/Sites/teamtalk-nodejs/node_modules/protobufjs/dist/ProtoBuf.js:3114:39)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/scorpio/Sites/teamtalk-nodejs/node_modules/protobufjs/dist/ProtoBuf.js:2462:49)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/scorpio/Sites/teamtalk-nodejs/node_modules/protobufjs/dist/ProtoBuf.js:3130:50)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/scorpio/Sites/teamtalk-nodejs/node_modules/protobufjs/dist/ProtoBuf.js:2460:52)
    at Function.Message.decode (/Users/scorpio/Sites/teamtalk-nodejs/node_modules/protobufjs/dist/ProtoBuf.js:2190:41)
    at Socket.<anonymous> (/Users/scorpio/Sites/teamtalk-nodejs/pb.js:82:46)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)

**Comment by dcodeIO** [comment]
Is this still an issue?
