### ISSUE TITLE
"Not a valid definition" Error, protoc works

### ISSUE THREAD

**Issue by MikeEmery** [dcodeIO/ProtoBuf.js#221]
I have a proto file defined as follows: 

    package AdsResponse;

    message Constraints {
      optional uint32 min_ads = 1;
      optional uint32 max_ads = 2;
    }

    message AdUnit {
      optional Constraints constraints = 1;
    }

    message AdsResponse {
      required uint32 status = 1;
      repeated AdUnit units = 2;
    }

I can compile the .proto file using the protoc command

    protoc --python_out=. ads_response.proto

However when I try to load the proto file in Javascript I get an error:

    Error: Not a valid definition: {"name":"Constraints","fields":[{"rule":"optional","options":{},"type":"uint32","name":"min_ads","id":1},{"rule":"optional","options":{},"type":"uint32","name":"max_ads","id":2}],"enums":[],"messages":[],"options":{},"oneofs":{}}
        at Error (<anonymous>)
        at ProtoBuf.Builder.BuilderPrototype.create (/Users/memery/projects/experiments/node_modules/protobufjs/dist/ProtoBuf.js:3918:39)
        at ProtoBuf.Builder.BuilderPrototype.import (/Users/memery/projects/experiments/node_modules/protobufjs/dist/ProtoBuf.js:4007:26)
        at Object.ProtoBuf.loadJson (/Users/memery/projects/experiments/node_modules/protobufjs/dist/ProtoBuf.js:4292:30)
        at Object.ProtoBuf.loadProto (/Users/memery/projects/experiments/node_modules/protobufjs/dist/ProtoBuf.js:4195:29)
        at Object.ProtoBuf.loadProtoFile (/Users/memery/projects/experiments/node_modules/protobufjs/dist/ProtoBuf.js:4241:56)
        at Object.<anonymous> (/Users/memery/projects/experiments/index.js:5:33)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)

This is the program I'm trying to run:

    var ProtoBuf = require('protobufjs')
    var fs = require('fs');
    var wstream = fs.createWriteStream('protobuffed.bin');

    var AdsResponseProto = ProtoBuf.loadProtoFile('./ads_response.proto').build("AdsResponse");

    var adsResponse = new AdsResponseProto()
    adsResponse.status = 0

    var binaryAdsResponse = adsResponse.encode()

    console.log(binaryAdsResponse);

    wstream.write(binaryAdsResponse.buffer)
    wstream.end()

I am using version 3.8.2.

**Comment by MikeEmery** [comment]
I redid everything from scratch and it works.  I'm confused but oh well.
