### ISSUE TITLE
Request: Add line & column numbers in error output

### ISSUE THREAD

**Issue by zyklus** [dcodeIO/protobuf.js#311]
If line & column numbers are added we could use protobuf.js as a basic proto linter :)

**Comment by nigel0913** [comment]
+1

version: 5.0.1

example:

I couldn't find which file use proto2 enum.

```javascript
/usr/local/lib/node_modules/protobufjs/dist/protobuf.js:4762
                            throw Error("proto3 message cannot reference proto
                                  ^
Error: proto3 message cannot reference proto2 enum
    at Error (native)
    at ProtoBuf.Builder.BuilderPrototype.resolveAll (/usr/local/lib/node_modules/protobufjs/dist/protobuf.js:4762:35)
    at null.<anonymous> (/usr/local/lib/node_modules/protobufjs/dist/protobuf.js:4747:26)
    at Array.forEach (native)
    at ProtoBuf.Builder.BuilderPrototype.resolveAll (/usr/local/lib/node_modules/protobufjs/dist/protobuf.js:4745:35)
    at null.<anonymous> (/usr/local/lib/node_modules/protobufjs/dist/protobuf.js:4747:26)
    at Array.forEach (native)
    at ProtoBuf.Builder.BuilderPrototype.resolveAll (/usr/local/lib/node_modules/protobufjs/dist/protobuf.js:4745:35)
    at null.<anonymous> (/usr/local/lib/node_modules/protobufjs/dist/protobuf.js:4747:26)
    at Array.forEach (native)
```

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
