### ISSUE TITLE
Nested message within TextFormat option not supported

### ISSUE THREAD

**Issue by w4-sjcho** [dcodeIO/protobuf.js#322]
``` protobuf
syntax = "proto3";

import "google/protobuf/descriptor.proto";

message MyOption {
  message HelloOption {
    string hello = 1;
  }
  repeated HelloOption hellos = 1;
}

extend google.protobuf.MessageOptions {
  MyOption my_option = 60000;
}

message MyOptionHolder {
  string message = 1;
  option (my_option) = {
    hellos: {  // line 20
      hello: 'Hello 1'
    }
    hellos: {
      hello: 'Hello 2'
    }
  };
}
```

protoc works fine, while protobuf.js throws:

```
Error: Parse error at line 20: illegal value: {
      at Error (native)
      at ProtoBuf.DotProto.ParserPrototype._readValue (node_modules/protobufjs/dist/ProtoBuf.js:899:42)
      at ProtoBuf.DotProto.ParserPrototype._parseOptionValue (node_modules/protobufjs/dist/ProtoBuf.js:971:79)
      at ProtoBuf.DotProto.ParserPrototype._parseOption (node_modules/protobufjs/dist/ProtoBuf.js:933:18)
      at ProtoBuf.DotProto.ParserPrototype._parseMessage (node_modules/protobufjs/dist/ProtoBuf.js:1103:26)
      at ProtoBuf.DotProto.ParserPrototype.parse (node_modules/protobufjs/dist/ProtoBuf.js:764:34)
      at Function.ProtoBuf.DotProto.Parser.parse (node_modules/protobufjs/dist/ProtoBuf.js:799:39)
      at Function.proto.load (node_modules/protobufjs/cli/pbjs/sources/proto.js:61:41)
      at node_modules/protobufjs/cli/pbjs/sources/proto.js:36:26
```

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
