### ISSUE TITLE
pbjs fails for message options

### ISSUE THREAD

**Issue by w4-sjcho** [dcodeIO/protobuf.js#323]
sample.proto:

``` protobuf
syntax = "proto3";

import "google/protobuf/descriptor.proto";

message MyOption {
  repeated string hello = 1;
}

extend google.protobuf.MessageOptions {
  MyOption my_option = 60000;
}

message MyOptionHolder {
  string message = 1;
  option (my_option) = {
    hello: 'world 1'
    hello: 'world 2'
  };
}
```

protoc works: `protoc --python_out=. sample.proto`

`pbjs sample.proto` fails with:

```
/Users/sjcho/repos/gabe/gabe_proto/node_modules/protobufjs/cli/pbjs/targets/json.js:136
                throw Error("Illegal option type: "+typeof(val));
                                                   ^
Error: Illegal option type: object
    at Error (native)
    at /Users/sjcho/repos/gabe/gabe_proto/node_modules/protobufjs/cli/pbjs/targets/json.js:136:52
    at Array.forEach (native)
    at buildOptions (/Users/sjcho/repos/gabe/gabe_proto/node_modules/protobufjs/cli/pbjs/targets/json.js:128:42)
    at buildNamespace (/Users/sjcho/repos/gabe/gabe_proto/node_modules/protobufjs/cli/pbjs/targets/json.js:66:33)
    at buildMessage (/Users/sjcho/repos/gabe/gabe_proto/node_modules/protobufjs/cli/pbjs/targets/json.js:167:5)
    at /Users/sjcho/repos/gabe/gabe_proto/node_modules/protobufjs/cli/pbjs/targets/json.js:73:23
    at Array.forEach (native)
    at buildNamespace (/Users/sjcho/repos/gabe/gabe_proto/node_modules/protobufjs/cli/pbjs/targets/json.js:72:46)
    at Object.module.exports [as json] (/Users/sjcho/repos/gabe/gabe_proto/node_modules/protobufjs/cli/pbjs/targets/json.js:43:5)
```

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
