### ISSUE TITLE
Support for reserved keywords

### ISSUE THREAD

**Issue by mhahn** [dcodeIO/protobuf.js#344]
https://developers.google.com/protocol-buffers/docs/proto3#reserved

i get the following error when trying to do something like the following:

```
message Test {
     reserved 1;
     string other_field = 2;
}
```

->

```
/User/.nvm/versions/io.js/v3.3.1/lib/node_modules/protobufjs/dist/ProtoBuf.js:782
                throw e;
                ^

Error: Parse error at line 5: illegal message field name: 1
    at Error (native)
    at ProtoBuf.DotProto.ParserPrototype._parseMessageField (/User/.nvm/versions/io.js/v3.3.1/lib/node_modules/protobufjs/dist/ProtoBuf.js:1184:68)
    at ProtoBuf.DotProto.ParserPrototype._parseMessage (/User/.nvm/versions/io.js/v3.3.1/lib/node_modules/protobufjs/dist/ProtoBuf.js:1107:26)
    at ProtoBuf.DotProto.ParserPrototype.parse (/User/.nvm/versions/io.js/v3.3.1/lib/node_modules/protobufjs/dist/ProtoBuf.js:760:34)
    at Function.ProtoBuf.DotProto.Parser.parse (/User/.nvm/versions/io.js/v3.3.1/lib/node_modules/protobufjs/dist/ProtoBuf.js:795:39)
    at Function.proto.load (/User/.nvm/versions/io.js/v3.3.1/lib/node_modules/protobufjs/cli/pbjs/sources/proto.js:61:41)
    at /User/.nvm/versions/io.js/v3.3.1/lib/node_modules/protobufjs/cli/pbjs/sources/proto.js:76:40
    at Function.proto.load (/User/.nvm/versions/io.js/v3.3.1/lib/node_modules/protobufjs/cli/pbjs/sources/proto.js:80:15)
    at /User/.nvm/versions/io.js/v3.3.1/lib/node_modules/protobufjs/cli/pbjs/sources/proto.js:76:40
    at Function.proto.load (/User/.nvm/versions/io.js/v3.3.1/lib/node_modules/protobufjs/cli/pbjs/sources/proto.js:80:15)
```

**Comment by dcodeIO** [comment]
Currently, the reserved keyword isn't supported. Marked is as an enhancement for future support.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.

**Comment by schwiet** [comment]
So what is the suggestion for proto files using `reserved`? I just updated to 6.0.0 and files that were previously compiling with pbjs are not and the error is related to `reserved` fields. 

`Error: illegal token ',', ';' expected (line 105)`

**Comment by dcodeIO** [comment]
Maybe try with latest instead, which is 6.6.3.

**Comment by schwiet** [comment]
Sorry for my confusing comment; I just meant to say that I updated from v5 to v6. I am using 6.6.3.  Is reserved supposed to be supported now? I am having trouble compiling files with `reserved` and with `allow_alias` in enums. These files did previously compile fine.
