### ISSUE TITLE
pbjs fails on ```import weak ...```

### ISSUE THREAD

**Issue by maxlang** [dcodeIO/protobuf.js#365]
According to the spec, `import` can be followed by either `public` or `weak`.

https://developers.google.com/protocol-buffers/docs/reference/proto2-spec#import_statement

`public` is handled in the parser already (https://github.com/dcodeIO/protobuf.js/blob/master/src/ProtoBuf/DotProto/Parser.js#L70) but when I have a weak import I get the following error:

```
$ pbjs ../sql/driver/wire.proto --path ../../../gogo/protobuf/

/Users/maxlang/go/src/github.com/cockroachdb/cockroach/ui/node_modules/protobufjs/dist/ProtoBuf.js:782
                throw e;
                ^

Error: Parse error at line 22: illegal string delimiter: weak
    at Error (native)
    at ProtoBuf.DotProto.ParserPrototype._readString (/Users/maxlang/go/src/github.com/cockroachdb/cockroach/ui/node_modules/protobufjs/dist/ProtoBuf.js:869:27)
    at ProtoBuf.DotProto.ParserPrototype.parse (/Users/maxlang/go/src/github.com/cockroachdb/cockroach/ui/node_modules/protobufjs/dist/ProtoBuf.js:747:42)
    at Function.ProtoBuf.DotProto.Parser.parse (/Users/maxlang/go/src/github.com/cockroachdb/cockroach/ui/node_modules/protobufjs/dist/ProtoBuf.js:795:39)
    at Function.proto.load (/Users/maxlang/go/src/github.com/cockroachdb/cockroach/ui/node_modules/protobufjs/cli/pbjs/sources/proto.js:61:41)
    at /Users/maxlang/go/src/github.com/cockroachdb/cockroach/ui/node_modules/protobufjs/cli/pbjs/sources/proto.js:36:26
    at Array.forEach (native)
    at Object.module.exports [as proto] (/Users/maxlang/go/src/github.com/cockroachdb/cockroach/ui/node_modules/protobufjs/cli/pbjs/sources/proto.js:35:15)
    at Object.pbjs.main (/Users/maxlang/go/src/github.com/cockroachdb/cockroach/ui/node_modules/protobufjs/cli/pbjs.js:245:47)
    at Object.<anonymous> (/Users/maxlang/go/src/github.com/cockroachdb/cockroach/ui/node_modules/protobufjs/bin/pbjs:2:51)
```

I'd be happy with behavior that just ignored `weak` for now, and I could probably write a PR to that effect, but I figured it might be simpler to run it by you guys first.

**Comment by maxlang** [comment]
Took a stab here, but wasn't sure how to build everything.

https://github.com/cockroachdb/protobuf.js/commit/659d311cd4fee32e2661a48ddcf007c12ad43977

**Comment by maxlang** [comment]
PR
https://github.com/dcodeIO/protobuf.js/pull/370

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
