### ISSUE TITLE
How to deal with streams? 

### ISSUE THREAD

**Issue by ariporad** [dcodeIO/protobuf.js#385]
Hi, Thanks so much for making such an awesome library!

Quick question though, what's the recommended method for dealing with sockets? Are you supposed to do something like this?:

```javascript
var chunks = [];
var lengthLeft;
socket.on('data', function (chunk) {
    var len = chunk.length;
    if (chunk.length < lengthLeft) return; chunks.push(chunk);
    // parse chunks
});
```

Or is there a built in method to do this?

Thanks!

**Comment by dcodeIO** [comment]
You could use a ByteBuffer to buffer the data and reset it every now and then.

```js
var bb = ProtoBuf.ByteBuffer.allocate(4096); // i.e. maximum expected message length
socket.on('data', function(chunk) {
  bb.append(data);
  try {
    var myMessage = MyMessage.decodeDelimited(bb)
    bb.offset = 0; // and then reuse it
    ...
  } catch (err) {
    // wait for more
  }
})

**Comment by ariporad** [comment]
@dcodeIO: Ok, Thanks! It might be worth adding that to the wiki, for others.

**Comment by ariporad** [comment]
@dcodeIO: Follow up, is there a way to determine the message type given a buffer?

**Comment by ariporad** [comment]
Also, what's `decodeDelimited`? I can't find docs.

**Comment by dcodeIO** [comment]
I updated the code example to something more performant and usable.

There is no functionality to decode an unknown buffer with lost type information, yet. It is however possible to do something this, but you won't get the types that you'd expect. For example both byte[] and string [share the same wire format](https://github.com/dcodeIO/protobuf.js/blob/master/src/protobuf.js#L103), and you'd just get a byte[]. For other data types this might become even more complicated.

**Comment by ariporad** [comment]
Thanks!

**Comment by vjpr** [comment]
@dcodeIO's [comment](https://github.com/dcodeIO/protobuf.js/issues/385#issuecomment-170306329) gave me this error:

```
/node_modules/.registry.npmjs.org/bytebuffer/5.0.1/node_modules/bytebuffer/dist/bytebuffer-node.js:2355
                throw RangeError("Illegal range: 0 <= "+begin+" <= "+end+" <= "+this.buffer.length);
                ^

RangeError: Illegal range: 0 <= 4111 <= 4084 <= 8192
    at ByteBuffer.module.exports.ByteBufferPrototype.compact (node_modules/.registry.npmjs.org/bytebuffer/5.0.1/node_modules/bytebuffer/dist/bytebuffer-node.js:2355:23)
    at Socket.<anonymous> (/index.js:36:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
^C
```

**Comment by kirillgroshkov** [comment]
Spent few hours looking for solution, and here's my working version:

```typescript
function transformFromProtobuf<OUT>(type: protobuf.Type): TransformTyped<Buffer, OUT> {
  let remainder = Buffer.alloc(0)

  return new Transform({
    objectMode: false,
    readableObjectMode: true,
    async transform(chunk: Buffer, _encoding, cb) {
      // console.log(chunk)
      const buf = Buffer.concat([remainder, chunk])

      let lastPos = 0
      const reader = protobuf.Reader.create(buf)
      try {
        while (reader.pos < reader.len) {
          lastPos = reader.pos
          const frame = type.decodeDelimited(reader)
          this.push(frame)
        }

        remainder = Buffer.alloc(0)
      } catch (err) {
        // console.log({pos: reader.pos, lastPos, len: reader.len}, 'got err')
        remainder = buf.slice(lastPos)
      }
      // console.log(`remainder size: ${remainder.length}`)
      cb() // finished processing
    },
  })
}

```
