### ISSUE TITLE
error encoding Object.create(null) objects

### ISSUE THREAD

**Issue by chpio** [dcodeIO/protobuf.js#404]
```
/home/thomas/ws/bg/node_modules/protobufjs/dist/protobuf-light.js:1557
                            if (keyOrObj.hasOwnProperty(ikey) && typeof (value = keyOrObj[ikey]) !== 'undefined')
                                         ^
TypeError: keyOrObj.hasOwnProperty is not a function
    at [object Object].MessagePrototype.set (/home/thomas/ws/bg/node_modules/protobufjs/dist/protobuf-light.js:1557:42)
    at [object Object].Message (/home/thomas/ws/bg/node_modules/protobufjs/dist/protobuf-light.js:1487:34)
    at encode (/home/thomas/ws/bg/src/lib/message-coder.js:27:17)
    at Object.<anonymous> (/home/thomas/ws/bg/src/server.js:29:38)
    at Module._compile (module.js:413:34)
    at loader (/home/thomas/ws/bg/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/thomas/ws/bg/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

https://github.com/dcodeIO/protobuf.js/blob/7df5707614f7739d0a90e4eaa9926c6c6729d8e7/dist/protobuf-light.js#L1557
should be (?!): 

``` javascript
keyOrObj::Object.hasOwnProperty(ikey)
```

EDIT: or the same in es5:

``` javascript
Object.hasOwnProperty.call(keyOrObj, ikey)
```

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
