### ISSUE TITLE
When call the method  Message.decode,it cause the error: RangeError: Illegal offset: 0 <= 2892 (+12) <= 2892

### ISSUE THREAD

**Issue by harter123** [dcodeIO/protobuf.js#413]
The problem is very strange .Sometimes the buffer  is short , the program  would run ok,but if the buffer is very long,such as 2892, the program would throw the RangeError. Why?

RangeError: Illegal offset: 0 <= 2892 (+12) <= 2892
    at RangeError (native)
    at module.exports.ByteBufferPrototype.readUTF8String (d:\interfaceSystem\interfacesystem\node_modules\protobufjs\node_modules\bytebuffer\dist\bytebuffer-node.js:2022:27)
    at module.exports.ByteBufferPrototype.readVString (d:\interfaceSystem\interfacesystem\node_modules\protobufjs\node_modules\bytebuffer\dist\bytebuffer-node.js:2114:24)
    at ProtoBuf.Reflect.ElementPrototype.decode (d:\interfaceSystem\interfacesystem\node_modules\protobufjs\dist\protobuf.js:2169:35)
    at ProtoBuf.Reflect.FieldPrototype.decode (d:\interfaceSystem\interfacesystem\node_modules\protobufjs\dist\protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (d:\interfaceSystem\interfacesystem\node_modules\protobufjs\dist\protobuf.js:3238:45)
    at ProtoBuf.Reflect.ElementPrototype.decode (d:\interfaceSystem\interfacesystem\node_modules\protobufjs\dist\protobuf.js:2185:46)
    at ProtoBuf.Reflect.FieldPrototype.decode (d:\interfaceSystem\interfacesystem\node_modules\protobufjs\dist\protobuf.js:3727:33)
    at ProtoBuf.Reflect.MessagePrototype.decode (d:\interfaceSystem\interfacesystem\node_modules\protobufjs\dist\protobuf.js:3233:48)
    at Function.Message.decode (d:\interfaceSystem\interfacesystem\node_modules\protobufjs\dist\protobuf.js:2933:37)

**Comment by choudhary001** [comment]
I too am facing this same issue. Has anyone found a solution for this?

RangeError: Illegal offset: 0 <= 156 (+6) <= 157
    at RangeError (native)
    at module.exports.ByteBufferPrototype.readUTF8String (/u/choudhab/node_modules/protobufjs/node_modules/bytebuffer/dist/bytebuffer-node.js:2117:27)
    at module.exports.ByteBufferPrototype.readVString (/u/choudhab/node_modules/protobufjs/node_modules/bytebuffer/dist/bytebuffer-node.js:2209:24)
    at ProtoBuf.Reflect.ElementPrototype.decode (/u/choudhab/node_modules/protobufjs/dist/protobuf.js:2169:35)
    at ProtoBuf.Reflect.FieldPrototype.decode (/u/choudhab/node_modules/protobufjs/dist/protobuf.js:3727:33)

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
