### ISSUE TITLE
Error: Illegal wire type for unknown field 

### ISSUE THREAD

**Issue by lxlhum** [dcodeIO/protobuf.js#465]
Error: Illegal wire type for unknown field 20 in Message .Quotes#decode: 7
    at Error (<anonymous>)
    at ProtoBuf.Reflect.MessagePrototype.decode (d:\billmartproject\03.development\01.master\bimart_web_quotation\node_modules\protobufjs\dist\protobuf.js:3228:35)
    at Function.ProtoBuf.Reflect.MessagePrototype.build.Message.decode (d:\billmartproject\03.development\01.master\bimart_web_quotation\node_modules\protobufjs\dist\protobuf.js:2933:37)
    at Object.exports.getQuotesResponeModelData (d:\billmartproject\03.development\01.master\bimart_web_quotation\lib\model\QuotaModel.js:11:26)
    at Socket.<anonymous> (d:\billmartproject\03.development\01.master\bimart_web_quotation\bimart.js:163:41)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.stream.pause.paused (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
