### ISSUE TITLE
Encode does not take plain object

### ISSUE THREAD

**Issue by tristanz** [dcodeIO/protobuf.js#491]
Using the published v6 code, I am not able to encode objects directly:

```
const Test = root.lookup('Test')
const data = Test.encode({a: 'tristanz'}).finish()
error TypeError: Cannot read property 'length' of undefined
    at byteLength (~/test/node_modules/protobufjs/src/writer.js:328:23)
```
Using `create` and then `encode` does work.

**Comment by dcodeIO** [comment]
What's the definition for Test#a ?

**Comment by tristanz** [comment]
Here's a full repro.  It appears related to leaving off fields.  This works with `create`, but fails with `encode`.

### Test.proto
```
syntax = "proto3";
message Test {
  string a = 1;
  string b = 2;
}
```

### test.js
```javascript
const protobuf = require('protobufjs')
protobuf.load('Test.proto', (err, root) => {
  try {
    const Test = root.lookup('Test')
    const data1 = Test.encode(Test.create({a: 'tristan'})).finish()
    console.log('works:', data1)
    const data2 = Test.encode({a: 'tristan'}).finish()
    console.log('fails:', data2)
  } catch (e) {
    console.error(e)
  }
})
```

### Running
```
Tristans-MacBook-Pro:repro tzajonc$ node test.js 
works: <Buffer 0a 07 74 72 69 73 74 61 6e>
TypeError: Cannot read property 'length' of undefined
    at byteLength (/Users/tzajonc/Dropbox/workspace/src/github.com/tristanz/qmarked/server/node_modules/protobufjs/src/writer.js:328:23)
    at BufferWriter.write_string_buffer [as string] (/Users/tzajonc/Dropbox/workspace/src/github.com/tristanz/qmarked/server/node_modules/protobufjs/src/writer.js:490:15)
    at _Test$ctor._Test$encode [as encode_] (eval at eof (/Users/tzajonc/Dropbox/workspace/src/github.com/tristanz/qmarked/server/node_modules/protobufjs/src/codegen.js:111:27), <anonymous>:8:14)
    at _Test$ctor.encode (/Users/tzajonc/Dropbox/workspace/src/github.com/tristanz/qmarked/server/node_modules/protobufjs/src/type.js:304:17)
    at Root.protobuf.load.e (/Users/tzajonc/Dropbox/workspace/src/github.com/tristanz/qmarked/server/repro/test.js:7:24)
    at finish (/Users/tzajonc/Dropbox/workspace/src/github.com/tristanz/qmarked/server/node_modules/protobufjs/src/root.js:291:12)
    at process (/Users/tzajonc/Dropbox/workspace/src/github.com/tristanz/qmarked/server/node_modules/protobufjs/src/root.js:316:17)
    at /Users/tzajonc/Dropbox/workspace/src/github.com/tristanz/qmarked/server/node_modules/protobufjs/src/root.js:332:17
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

**Comment by tristanz** [comment]
Tested against master with same result.

**Comment by dcodeIO** [comment]
I see, it doesn't set the default there and encoding intentionally skips checks to be faster. Will add one for this case now!

**Comment by tristanz** [comment]
Thanks!  Also it appears that exceptions are being swallowed somewhere.  If you don't have that try, catch block in the callback it will exit without any visible error.  This took me a while to debug.
