### ISSUE TITLE
6.1.0 encode failed in generated static .js files

### ISSUE THREAD

**Issue by twoeo** [dcodeIO/protobuf.js#551]
### Any static js encode will be failed at 6.1.0, the same js file works well at 6.0.2

**Environment**
Nodejs 6.7.0

**Proto**

```proto
syntax = "proto3";

message Test {
    string value = 1;
}
```

**Generated static js file**
(Genereated by ``pbjs -t static test.js``)
```proto
;(function(global, factory) {

    /* AMD */ if (typeof define === 'function' && define.amd)
        define(["protobuf"], factory);
    
    /* CommonJS */ else if (typeof require === 'function' && typeof module === 'object' && module && module.exports)
        module.exports = factory(require("protobufjs/runtime"));
    
    /* Global */ else
        global.root = factory(global.protobuf);

})(this, function($runtime) {
    "use strict";

    // Lazily resolved type references
    var $lazyTypes = [];

    // Exported root namespace
    var $root = {};

    /** @alias Test */
    $root.Test = (function() {

        /**
         * Constructs a new Test.
         * @exports Test
         * @constructor
         * @param {Object} [properties] Properties to set
         */
        function Test(properties) {
            if (properties) {
                var keys = Object.keys(properties);
                for (var i = 0; i < keys.length; ++i)
                    this[keys[i]] = properties[keys[i]];
            }
        }

        Test.prototype.value = "";

        /**
         * Encodes the specified Test.
         * @function
         * @param {Test|Object} message Test or plain object to encode
         * @param {Writer} [writer] Writer to encode to
         * @returns {Writer} Writer
         */
        Test.encode = (function() {
            /* eslint-disable */
            var Writer = $runtime.Writer;
            var util = $runtime.util;
            var types; $lazyTypes.push(types = [null]);
            return function encode(m,w) {
                w||(w=Writer())
                if(m['value']!==undefined&&m['value']!=="")
                    w.tag(1,2).string(m['value'])
                return w
            }
            /* eslint-enable */
        })();

        /**
         * Encodes the specified Test, length delimited.
         * @param {Test|Object} message Test or plain object to encode
         * @param {Writer} [writer] Writer to encode to
         * @returns {Writer} Writer
         */
        Test.encodeDelimited = function encodeDelimited(message, writer) {
            return this.encode(message, writer).ldelim();
        };

        /**
         * Decodes a Test from the specified reader or buffer.
         * @function
         * @param {Reader|Uint8Array} readerOrBuffer Reader or buffer to decode from
         * @param {number} [length] Message length if known beforehand
         * @returns {Test} Test
         */
        Test.decode = (function() {
            /* eslint-disable */
            var Reader = $runtime.Reader;
            var util = $runtime.util;
            var types; $lazyTypes.push(types = [null]);
            return function decode(r,l) {
                r instanceof Reader||(r=Reader(r))
                var c=l===undefined?r.len:r.pos+l,m=new $root.Test
                while(r.pos<c){
                    var t=r.tag()
                    switch(t.id){
                        case 1:
                            m['value']=r.string()
                            break
                        default:
                            r.skipType(t.wireType)
                            break
                    }
                }
                return m
            }
            /* eslint-enable */
        })();

        /**
         * Decodes a Test from the specified reader or buffer, length delimited.
         * @param {Reader|Uint8Array} readerOrBuffer Reader or buffer to decode from
         * @returns {Test} Test
         */
        Test.decodeDelimited = function decodeDelimited(readerOrBuffer) {
            readerOrBuffer = readerOrBuffer instanceof Reader ? readerOrBuffer : Reader(readerOrBuffer);
            return this.decode(readerOrBuffer, readerOrBuffer.uint32());
        };

        /**
         * Verifies a Test.
         * @param {Test|Object} message Test or plain object to verify
         * @returns {?string} `null` if valid, otherwise the reason why it is not
         */
        Test.verify = (function() {
            /* eslint-disable */
            var types; $lazyTypes.push(types = [null]);
            return function verify(m) {
                return null
            }
            /* eslint-enable */
        })();

        return Test;
    })();

    // Resolve lazy types
    $lazyTypes.forEach(function(types) {
        types.forEach(function(path, i) {
            if (!path)
                return;
            path = path.split('.');
            var ptr = $root;
            while (path.length)
                ptr = ptr[path.shift()];
            types[i] = ptr;
        });
    });

    return $root;
});
```

**Problem code**
```js
var Test = require('./test').Test;
Test.encode({value:'xxx'});
```

**Result**
> TypeError: Cannot set property 'len' of undefined
    at Writer (E:\Codes\ChartMaker\realtimeServer\node_modules\protobufjs\src\writer.js:105:14)
    at Function.encode (E:\Codes\ChartMaker\realtimeServer\src\proto\test.js:53:23)
    at repl:1:6
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)

**Comment by dcodeIO** [comment]
The writer API has changed between 6.0.2 and 6.1.0 in that it requires calling `Writer.create()` instead of `Writer()` (as a function).
