### ISSUE TITLE
Trouble Parsing Enums

### ISSUE THREAD

**Issue by griffnb** [dcodeIO/protobuf.js#565]
protobuf.js version: 6.2.0

Protobuff is failing to parse prototype files that are included.  They are standard files and parsed fine before version 6.0
[prototypeFiles.zip](https://github.com/dcodeIO/protobuf.js/files/658174/prototypeFiles.zip)

```js
// Decode the Message
 ProtoBuf.load('beeswax/bid/request.proto').then(root=>{
     var BidAgentRequest = root.lookup('bid.BidAgentRequest');
     console.log(BidAgentRequest);
}).catch(e=>{
    console.trace(e);
 })
```

```
failed to load Error: illegal name ';' (line 448)
    at Error (native)
    at illegal (/Users/xxxx/node_modules/protobufjs/src/parse.js:67:16)
    at parseEnumField (/Users/xxxx/node_modules/protobufjs/src/parse.js:342:19)
    at parseEnum (/Users/xxxx/node_modules/protobufjs/src/parse.js:332:21)
    at parseCommon (/Usersxxxxs/CoreNodeServe/node_modules/protobufjs/src/parse.js:207:17)
    at parseType (/Users/xxxxx/node_modules/protobufjs/src/parse.js:229:21)
    at parseCommon (/Users/xxxx/node_modules/protobufjs/src/parse.js:203:17)
    at parseType (/Users/xxxxx/node_modules/protobufjs/src/parse.js:229:21)
    at parseCommon (/Users/xxxxxxx/node_modules/protobufjs/src/parse.js:203:17)
    at parseType (/Users/xxxxxxx/node_modules/protobufjs/src/parse.js:229:21)
    at parseCommon (/Users/xxxxx/node_modules/protobufjs/src/parse.js:203:17)
    at parse (/Users/xxxxxxx/node_modules/protobufjs/src/parse.js:526:21)
    at process (/Users/xxxxxxxxnode_modules/protobufjs/src/root.js:92:48)
    at /Users/xxxxxxxxxxx/node_modules/protobufjs/src/root.js:162:17
    at fetchReadFileCallback (/Users/xxxxxxx/node_modules/@protobufjs/fetch/index.js:30:19)
```

**Comment by dcodeIO** [comment]
Tracked this down to

```protobuf
enum {
  option foo = "bar"; // at semi
}
```

**Comment by dcodeIO** [comment]
Should now be fixed in master.
