### ISSUE TITLE
Please, help! Cant decode

### ISSUE THREAD

**Issue by levide** [dcodeIO/protobuf.js#578]
protobuf.js version: ^6.2.1
**buffer**
083515604859581840220a0d6048595815bdf426422a0a0d7047595815bdf426

**code:**

```
protobuf.load("PulseFlagData.proto", function(err, root) {
                            if (err) {
                                callback(err);
                            }
                            var pulse = root.lookup("PulseFlagData");
                            
                            callback(null, pulse.decode(parsed_data.payload)); 
 });   
```

**.proto file:**
```
syntax = "proto3";

message PulseFlagSample {
	required fixed32 timestamp = 1;
	required uint32 input = 2;
	required bool flag = 3;
}

message PulseFlagData {
    required uint32 config_version = 1;
    required fixed32 device_time = 2;
    required PulseFlagSample current = 3;
    optional PulseFlagSample last_hour = 4;
}
```

**error:**
```
/home/deck/NetBeansProjects/lora/node_modules/protobufjs/src/reader.js:390
            throw indexOutOfRange(this, length);
            ^

RangeError: index out of range: 23 + 10 > 32
    at RangeError (native)
    at indexOutOfRange (/home/deck/NetBeansProjects/lora/node_modules/protobufjs/src/reader.js:13:12)
    at BufferReader.skip (/home/deck/NetBeansProjects/lora/node_modules/protobufjs/src/reader.js:390:19)
    at BufferReader.ReaderPrototype.skipType (/home/deck/NetBeansProjects/lora/node_modules/protobufjs/src/reader.js:410:18)
    at Type._PulseFlagSample$decode [as decode] (eval at eof (/home/deck/NetBeansProjects/lora/node_modules/protobufjs/node_modules/@protobufjs/codegen/index.js:102:25), <anonymous>:19:7)
    at Type.decode_setup [as decode] (/home/deck/NetBeansProjects/lora/node_modules/protobufjs/src/type.js:370:7)
    at Type._PulseFlagData$decode [as decode] (eval at eof (/home/deck/NetBeansProjects/lora/node_modules/protobufjs/node_modules/@protobufjs/codegen/index.js:102:25), <anonymous>:16:27)
    at Type.decode_setup [as decode] (/home/deck/NetBeansProjects/lora/node_modules/protobufjs/src/type.js:370:7)
    at /home/deck/NetBeansProjects/lora/server.js:42:50
    at finish (/home/deck/NetBeansProjects/lora/node_modules/protobufjs/src/root.js:84:9)
```

**Comment by miguelportilla** [comment]
Not sure if this is your problem but you are specifying proto3 syntax in your .proto file and using proto2 language.

**Comment by dcodeIO** [comment]
```
08	id 1, wireType 0 (varint)
35	53
15	id 2, wireType 5 (fixed32)
60	
48
59
58
18	id 3, wireType 0 (varint)
40	64
22	id 4, wireType 2 (ldelim)
0a	length 10
0d
60
48
59
58
15
bd
f4
26
42
2a	id 5, wireType 2 (ldelim)
0a	length 10
0d	1st
70	2nd
47	3rd
59	4th
58	5th
15	6th
bd	7th
f4	8th
26	9th
```
Your buffer is truncated.

**Comment by dcodeIO** [comment]
Closing this issue for now. Feel free to reopen it if necessary!

**Comment by levide** [comment]
@dcodeIO @miguelportilla thank you!  I received wrong .proto for divice from manufuctor
