### ISSUE TITLE
New Enum breakage in static code.

### ISSUE THREAD

**Issue by ehallander9591** [dcodeIO/protobuf.js#641]
protobuf.js version: 6.5.0

After pulling the latest from git, I find that the generated static code is referencing 'values' while trying to resolve the numeric part of an enum.

In the code below types[2].values should simply be types[2][message.changeType]

```js
                            case "changeType":
                                if (message.changeType !== undefined && message.changeType !== null) {
                                    object.changeType = options.enums === String ? types[2].values[message.changeType] : message.changeType;
                                }
                                break;

```

```
<please paste the stack trace of the error if applicable>
```

**Comment by ehallander9591** [comment]
Getting more than that. Sorry

```
TypeError: Cannot read property 'prototype' of undefined
    at Function.toObject (C:\Users\eric_hallander\git\MPXSCore\srcGen\js\mpxsStaticModule.js:10757:65)
    at PublishedMessage.toJSON (C:\Users\eric_hallander\git\MPXSCore\srcGen\js\mpxsStaticModule.js:10809:49)
    at Object.stringify (native)
    at Object.stringify (C:\Users\eric_hallander\git\MPXSCore\tsapp\fw\util.ts:96:14)
    at MpxsSessionManagerImpl.sendSocket (C:\Users\eric_hallander\git\MPXSCore\tsapp\MpxsServer.ts:218:50)
    at PublishSubscribeAdapter.socket.on (C:\Users\eric_hallander\git\MPXSCore\tsapp\mpxs\PublishSubscribeAdapter.ts:52:25)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Socket._flushRead (C:\Users\eric_hallander\git\MPXSCore\node_modules\zmq\lib\index.js:636:10)
    at Socket._flushReads (C:\Users\eric_hallander\git\MPXSCore\node_modules\zmq\lib\index.js:676:23)
```

and when I look at the generated code for this one

```
                            case "unit":
                                if (message.unit !== undefined && message.unit !== null) {
                                    object.unit = types[12].ctor.prototype.toObject.call(message.unit, options);
                                }
                                break;
```

**Comment by dcodeIO** [comment]
Always amazing how many stupid mistakes there still are 😲

**Comment by ehallander9591** [comment]
I'll check this out when I get home.

**Comment by ehallander9591** [comment]
Looks good sir.

Thanks!!
