### ISSUE TITLE
Extensions inside the scope of the extension's field type fails

### ISSUE THREAD

**Issue by ufenegga** [dcodeIO/protobuf.js#657]
protobuf.js version: 6.6.1

I apologized for my weak english. 

Google doc says that this is a common pattern : 
```
message Baz {
  extend Foo {
    optional Baz foo_ext = 127;
  }
  ...
}
```
I have a proto build following this pattern that seems to fool pbjs when using ```-t static```. With ```-t json```, it works fine...

```js

message CompletionRequest {

  extend common.RpcBlog { optional CompletionRequest rpc_id = 1145; }

 // there are some more fields
 // ... 
}
```
Here is the stack 
```
Error: unresolvable field type: CompletionRequest
    at Error (native)
    at Field.resolve (/Users/francois.chabbey/thoughtspot/blink/node_modules/protobufjs/src/field.js:229:19)
    at /Users/francois.chabbey/thoughtspot/blink/node_modules/protobufjs/cli/targets/static.js:290:15
    at Array.forEach (native)
    at buildType (/Users/francois.chabbey/thoughtspot/blink/node_modules/protobufjs/cli/targets/static.js:289:22)
    at buildNamespace (/Users/francois.chabbey/thoughtspot/blink/node_modules/protobufjs/cli/targets/static.js:106:9)
    at /Users/francois.chabbey/thoughtspot/blink/node_modules/protobufjs/cli/targets/static.js:123:13
    at Array.forEach (native)
    at buildNamespace (/Users/francois.chabbey/thoughtspot/blink/node_modules/protobufjs/cli/targets/static.js:119:20)
    at /Users/francois.chabbey/thoughtspot/blink/node_modules/protobufjs/cli/targets/static.js:123:13


```

**Comment by dcodeIO** [comment]
Hard to tell, the error refers to `ValidateContextRequest`. Do you have additional context - or could you provide a minimal failing .proto file for reference?

**Comment by ufenegga** [comment]
Thanks for your response.. i'll come back with a self-contained example.

**Comment by ufenegga** [comment]
So this works 
```node ./node_modules/protobufjs/bin/pbjs -t static ./test.proto
```

```
message Foo {
  extensions 100 to 199;
}

message Baz {
  extend Foo {  optional Baz bar = 126; }

  optional int32 request_call_id = 2;
}```

**Comment by dcodeIO** [comment]
Might be related: https://github.com/dcodeIO/protobuf.js/issues/595

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
