### ISSUE TITLE
PBTS command line throws error unable to load template

### ISSUE THREAD

**Issue by HLFrye** [dcodeIO/protobuf.js#707]
protobuf.js version: 6.7.0

After upgrading to protobuf.js 6.7.0, while running this command:
node_modules/.bin/pbts ./path/to/static-JS-module-generated-by-pbjs.js

We get the following exception:

FATAL: Unable to load template: Cannot find module './lib/tsd-jsdoc/publish'
/Users/user/Dev/project/node_modules/protobufjs/cli/pbts.js:125
                throw err;
                ^

Error: code 1
    at ChildProcess.<anonymous> (/Users/user/Dev/project/node_modules/protobufjs/cli/pbts.js:120:27)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)

Running on:
OS: OS X El Capitan (10.11.6)
node: 7.1.0
npm: 3.10.9
bash: 3.2.57(1)-release (x86_64-apple-darwin15)

**Comment by dcodeIO** [comment]
It's a bit unclear where jsdoc pulls this from. Please let me know if this fixes it.

**Comment by dcodeIO** [comment]
Should be fixed in master.
