### ISSUE TITLE
The demo given by readme.md can not run ok

### ISSUE THREAD

**Issue by yunnysunny** [dcodeIO/protobuf.js#754]
protobuf.js version: 6.7.3

The demo given by readme.md can not run ok. It's unbelievable.

```js
const protobuf = require('protobufjs');
protobuf.load("./src/test/program/awesome.proto", function(err, root) {
    if (err)
        throw err;

    // Obtain a message type
    var AwesomeMessage = root.lookupType("awesomepackage.AwesomeMessage");

    // Exemplary payload
    var payload = { awesomeField: "AwesomeString" };

    // Verify the payload if necessary (i.e. when possibly incomplete or invalid)
    var errMsg = AwesomeMessage.verify(payload);
    if (errMsg)
        throw Error(errMsg);

    // Create a new message
    var message = AwesomeMessage.creeate(payload); // or use .fromObject if conversion is necessary

    // Encode a message to an Uint8Array (browser) or Buffer (node)
    var buffer = AwesomeMessage.encode(message).finish();
    // ... do something with buffer

    // Decode an Uint8Array (browser) or Buffer (node) to a message
    var message = AwesomeMessage.decode(buffer);
    // ... do something with message

    // If the application uses length-delimited buffers, there is also encodeDelimited and decodeDelimited.

    // Maybe convert the message back to a plain object
    var object = AwesomeMessage.toObject(message, {
        longs: String,
        enums: String,
        bytes: String,
        // see ConversionOptions
    });
});
```

```
    var message = AwesomeMessage.creeate(payload); // or use .fromObject if conversion is necessary
                                 ^

TypeError: AwesomeMessage.creeate is not a function
    at e:\kuaipan\code\node3\logical_server\src\test\program\prort.js:18:34
    at finish (E:\kuaipan\code\node3\logical_server\node_modules\.6.7.3@protobufjs\src\root.js:94:9)
    at process (E:\kuaipan\code\node3\logical_server\node_modules\.6.7.3@protobufjs\src\root.js:122:13)
    at E:\kuaipan\code\node3\logical_server\node_modules\.6.7.3@protobufjs\src\root.js:181:17
    at fetchReadFileCallback (E:\kuaipan\code\node3\logical_server\node_modules\.1.1.0@@protobufjs\fetch\index.js:51:19)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

```

**Comment by ehallander9591** [comment]
A better approach to this might be

"Hey dude, I see a slight typo in your Awesome example. AwesomeMessage.cre**e**ate

Great Library!!

**Comment by dcodeIO** [comment]
Fixed
