### ISSUE TITLE
Doesn't find Enum from imported proto file using protobuf cli

### ISSUE THREAD

**Issue by ValeryLosik** [dcodeIO/protobuf.js#760]
protobuf.js version: <6.7.3>

Expected to get generated file from proto
```.
syntax = "proto2";

import "pt/live/generator.proto";
import "pt/live/common.proto";
import "pt/live/types.proto";

package pt.live;

//java package
option java_package = "com.playtech.live.proto.user";
option objc_class_prefix = "LV2";

service UserService {
    option (pt.live.service) = "pt.live.user";

****
```

```
> protocol@1.0.0 protojs C:\Users\valeriil\projects\protocol
> node ./node_modules/protobufjs/bin/pbjs --t json-module -w commonjs -o pbjs/compiled.js -p protocol-client/src/main/proto  protocol-client/src/main/proto/pt/live/UserService.proto

C:\Users\valeriil\projects\protocol\node_modules\protobufjs\cli\pbjs.js:229
            throw err;
            ^

Error: no such Type or Enum 'MessageHeader' in Type .pt.live.LoginRequest
    at Error (native)
    at Type.lookupTypeOrEnum (C:\Users\valeriil\projects\protocol\node_modules\protobufjs\src\namespace.js:382:15)
    at Field.resolve (C:\Users\valeriil\projects\protocol\node_modules\protobufjs\src\field.js:248:94)
    at Type.resolveAll (C:\Users\valeriil\projects\protocol\node_modules\protobufjs\src\type.js:255:21)
    at Namespace.resolveAll (C:\Users\valeriil\projects\protocol\node_modules\protobufjs\src\namespace.js:286:25)
    at Namespace.resolveAll (C:\Users\valeriil\projects\protocol\node_modules\protobufjs\src\namespace.js:286:25)
    at Root.resolveAll (C:\Users\valeriil\projects\protocol\node_modules\protobufjs\src\namespace.js:286:25)
    at Root.resolveAll (C:\Users\valeriil\projects\protocol\node_modules\protobufjs\src\root.js:246:43)
    at Object.main (C:\Users\valeriil\projects\protocol\node_modules\protobufjs\cli\pbjs.js:220:48)
    at Object.<anonymous> (C:\Users\valeriil\projects\protocol\node_modules\protobufjs\bin\pbjs:4:16)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\valeriil\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "protojs"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! protocol@1.0.0 protojs: `node ./node_modules/protobufjs/bin/pbjs --t json-module -w commonjs -o pbjs/compiled.js -p protocol-client/src/main/proto  protocol-client/src/main/proto/pt/live/UserService.proto`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protocol@1.0.0 protojs script 'node ./node_modules/protobufjs/bin/pbjs --t json-module -w commonjs -o pbjs/compiled.js -p protocol-client/src/main/proto  protocol-client/src/main/proto/pt/live/UserService.proto'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the protocol package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./node_modules/protobufjs/bin/pbjs --t json-module -w commonjs -o pbjs/compiled.js -p protocol-client/src/main/proto  protocol-client/src/main/proto/pt/live/UserService.proto
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs protocol
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls protocol
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\valeriil\projects\protocol\npm-debug.log

```
MessageHeader is defined inside inside common.proto
This is how i run protobuf
```
node ./node_modules/protobufjs/bin/pbjs -t static-module -w commonjs -o pbjs/compiled.js -p protocol-client/src/main/proto protocol-client/src/main/proto/pt/live/UserService.proto
```
Project structure

```
protocol-client/
    src/
        main/
               proto/
                        pt/
                           live/
                                 common.proto
                                 UserService.proto
                                 ****
                       
```

**Comment by ehallander9591** [comment]
As far as I recall the tool does not "import" the import file statements, so you need to specify all the proto input files on the command line.

**Comment by dcodeIO** [comment]
Working for me using the following simple test case (assumes `MessageHeader` is also in the `.pt.live` namespace):

```protobuf
// common.proto
package pt.live;

enum MessageHeader {
    ONE = 1;
}
```

```protobuf
// other.proto
package pt.live;

import "common.proto";

message LoginRequest {
    optional MessageHeader header = 1;
}
```

```
$> pbjs -t json-module -w commonjs -p ptliveTestDirectory other.proto
```

Could you provide additional context from common.proto?

> As far as I recall the tool does not "import" the import file statements, so you need to specify all the proto input files on the command line.

It should actually import them from cwd and where `-p, --path` points.

**Comment by ehallander9591** [comment]
I might have to go back and re-try. We wrote the build task many protobufjs moons ago, and it seemed then the only way to get the output was to provide all the .proto file names on the command line.

It could be that we run from two directories higher with relative path to the top level proto file and then that had issues. I will try again.

**Comment by ehallander9591** [comment]
And it appears to act as you say. I am updating our build task.

**Comment by ValeryLosik** [comment]
Thanks,guys..issue was on our side,some imports should be resolved by maven,that's why protobufjs throwed errors
