### ISSUE TITLE
Got an error when generating static module

### ISSUE THREAD

**Issue by updogliu** [dcodeIO/protobuf.js#761]
protobuf.js version: 6.8.0

System: macOS 10.12

npm version
{ npm: '4.2.0',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '51',
  node: '7.8.0',
  openssl: '1.0.2k',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.11.0',
  v8: '5.5.372.43',
  zlib: '1.2.11' }

`pbjs -t json types.proto > types.json` works fine.
`pbjs -t static-module -w commonjs -o compiled.js types.proto` gives the following error

<path>/protobuf.js/cli/pbjs.js:229
            throw err;
            ^

TypeError: Cannot read property 'generate' of undefined
    at buildType (<path>/protobuf.js/cli/targets/static.js:370:41)
    at buildNamespace (<path>/protobuf.js/cli/targets/static.js:108:9)
    at <path>/protobuf.js/cli/targets/static.js:125:13
    at Array.forEach (native)
    at buildNamespace (<path>/protobuf.js/cli/targets/static.js:121:20)
    at static_target (<path>/protobuf.js/cli/targets/static.js:47:9)
    at static_module_target (<path>/protobuf.js/cli/targets/static-module.js:16:24)
    at callTarget (<path>/protobuf.js/cli/pbjs.js:290:9)
    at Object.main (<path>/protobuf.js/cli/pbjs.js:223:13)
    at Object.<anonymous> (<path>/protobuf.js/bin/pbjs:4:16)

**Comment by dcodeIO** [comment]
This should be fixed in master.

**Comment by updogliu** [comment]
Since 6.8.0 is the default version in npm, better to release the fix to npm.

**Comment by updogliu** [comment]
Yeah, it has been fixed.
