### ISSUE TITLE
Error: illegal buffer

### ISSUE THREAD

**Issue by josete89** [dcodeIO/protobuf.js#776]
Error: illegal buffer
    at Error (native)
    at Function.create_typed_array [as create] (http://localhost:63344/angular_app/app/protobuf.js:4577:15)
    at Type._Customer$decode [as decode] (eval at eof (http://localhost:63344/angular_app/app/protobuf.js:314:25), <anonymous>:5:12)
    at Type.decode_setup [as decode] (http://localhost:63344/angular_app/app/protobuf.js:6418:25)

**Comment by dcodeIO** [comment]
A bit more context would be quite helpful.

**Comment by josete89** [comment]
Stupid one, I forgot to wrap response.data into Uint8Array. 

Thanks
