### ISSUE TITLE
Got util.longNeq is not a function when running "pbjs -t proto2"

### ISSUE THREAD

**Issue by updogliu** [dcodeIO/protobuf.js#809]
protobuf.js version: v6.7.0

```pbjs -t proto2``` threw  "TypeError: util.longNeq is not a function"
```pbjs -t json``` with the same rest arguments worked successfully.

Stack trace
```
/usr/lib/node_modules/protobufjs/cli/pbjs.js:229
            throw err;
            ^

TypeError: util.longNeq is not a function
    at /usr/lib/node_modules/protobufjs/cli/targets/proto.js:242:41
    at Array.forEach (native)
    at buildFieldOptions (/usr/lib/node_modules/protobufjs/cli/targets/proto.js:230:10)
    at buildField (/usr/lib/node_modules/protobufjs/cli/targets/proto.js:207:16)
    at build (/usr/lib/node_modules/protobufjs/cli/targets/proto.js:115:9)
    at Array.forEach (native)
    at buildType (/usr/lib/node_modules/protobufjs/cli/targets/proto.js:178:22)
    at build (/usr/lib/node_modules/protobufjs/cli/targets/proto.js:113:9)
    at Array.forEach (native)
    at buildNamespace (/usr/lib/node_modules/protobufjs/cli/targets/proto.js:131:57)
```

**Comment by dcodeIO** [comment]
This function has been deprecated and ultimately removed. Ideally, update to a more recent version and regenerate any static code.

**Comment by jhherren** [comment]
Using version 6.8.6
util.longNeq is still here: https://github.com/dcodeIO/protobuf.js/blob/master/cli/targets/proto.js#L244
and causes errors when converting to proto2.
