### ISSUE TITLE
toObject function missing

### ISSUE THREAD

**Issue by yunnysunny** [dcodeIO/protobuf.js#835]
protobuf.js version: 6.8.0

`toObject` function missing when use 6.8.0, but when I change to 6.7.3 , it works ok.

```protobuf
syntax = "proto3";
package kodec;

message CommunicationFrame {
    uint32 msg_type =1;//{Number} 
    string msg_no = 2;//{String} 
    string msg_from_user_id =3;//{String} 
    string msg_to_user_id =4;//{String} 
    uint32 device_type = 5;// {Number} 
    uint32 version = 6;// {Number} 
}

message RequestPackage {//
    CommunicationFrame head_frame = 1;
    bytes logical_frame = 2;
}

message RequestMessage {
    string token = 1;
}
```
**The file of logical.proto**

```js
const protobuf = require('protobufjs');
var root = new protobuf.Root();
root.load("./proto/logical.proto", { keepCase: true }, function(err, root) {
    if (err)
        throw err;

    // Obtain a message type
    var RequestPackage = root.lookupType("kodec.RequestPackage");
    var RequestMessage = root.lookupType("kodec.RequestMessage");
    // Exemplary payload
    var payload = {
        "token":"test-0.xxx"
    };

    // Verify the payload if necessary (i.e. when possibly incomplete or invalid)
    var errMsg = RequestMessage.verify(payload);
    if (errMsg)
        throw Error(errMsg);

    // Create a new message
    var message = RequestMessage.create(payload); // or use .fromObject if conversion is necessary

    // Encode a message to an Uint8Array (browser) or Buffer (node)
    var buffer = RequestMessage.encode(message).finish();
    // ... do something with buffer
    //console.log('message buffer',buffer.toString('hex'));
    var packageRequst = RequestPackage.create({
        head_frame : {
            msg_type:20,
            msg_no : '1111',
            msg_from_user_id : 'aaa',
            device_type : 1,
            version : 1
        },
        logical_frame : buffer
    });
    // Decode an Uint8Array (browser) or Buffer (node) to a message
    var packageBuffer = RequestPackage.encode(packageRequst).finish();

    var messageDec = RequestPackage.decode(packageBuffer);
    console.log('messageDec',messageDec.toObject());
    // ... do something with message
    const request = RequestMessage.decode(messageDec.logical_frame);
    console.log('request:',request.toObject({longs: String}));
    // If the application uses length-delimited buffers, there is also encodeDelimited and decodeDelimited.

    // Maybe convert the message back to a plain object
    var object = RequestPackage.toObject(messageDec, {
        longs: String,
        enums: String,
        //bytes: String,
        // see ConversionOptions
    });//console.log(object);
});
```
**The file of pror3.js**

```
{lamb} node prort3.js
F:\temp\tproto\prort3.js:41
    console.log('messageDec',messageDec.toObject());
                                        ^

TypeError: messageDec.toObject is not a function
    at F:\temp\tproto\prort3.js:41:41
    at finish (F:\temp\tproto\node_modules\._protobufjs@6.8.0@protobufjs\src\root.js:95:9)
    at process (F:\temp\tproto\node_modules\._protobufjs@6.8.0@protobufjs\src\root.js:123:13)
    at F:\temp\tproto\node_modules\._protobufjs@6.8.0@protobufjs\src\root.js:182:17
    at fetchReadFileCallback (F:\temp\tproto\node_modules\._@protobufjs_fetch@1.1.0@@protobufjs\fetch\index.js:51:19)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
```
**The stack of error**

**Comment by dcodeIO** [comment]
https://github.com/dcodeIO/protobuf.js/issues/832
https://github.com/dcodeIO/protobuf.js/issues/828#issuecomment-307877338
