### ISSUE TITLE
Question: Proto file imports other proto files.

### ISSUE THREAD

**Issue by Arun-KumarH** [dcodeIO/protobuf.js#841]
protobuf.js version: 6.8.0

My job.proto file location is below and it imports "google/protobuf/any.proto" file.

Physical location of both files:
protos/io/restorecommerce/job.proto
protos/google/protobuf/any.proto

CONTENTS OF job.proto.
```
import "google/protobuf/any.proto";
message Job {
  /// Job Priority
  enum Priority {
    NORMAL = 0;
    LOW = 10;
    MEDIUM = -5;
    HIGH = -10;
    CRITICAL = -15;
  }
 
  string id = 1; /// Job resource ID
  double created = 2; /// Date of the Job creation
  double modified = 3; /// Last time the Job was modified
  string creator = 4; /// User ID of the creator

  google.protobuf.Any data = 12; /// Payload send to the worker.
  
}
```

Code snippet for resolving and loading proto file:
```
protoFilePath = "protos/io/restorecommerce/job.proto";
let root = new protobuf.Root();
root.resolvePath = function (origin, target) {
    return protoFilePath;
};
root = yield protobuf.load(protoFilePath, root).then(function (root) {
    return root;
}).catch(function (err) {
    console.log(err);
});
const MessageClass = root.lookupType(messageObject);
const convertedMessage = MessageClass.create(msg);
const buffer = MessageClass.encode(convertedMessage).finish();
```

But I am not able to resolve the imported any.proto file fields, am I missing anything in above code snippet while resolving paths ?

{ '0': 'Error: no such Type or Enum \'google.protobuf.Any\' in Type .io.restorecommerce.job.Job\n    at Type.lookupTypeOrEnum (/restore/scheduling-srv/node_modules/protobufjs/src/namespace.js:380:15)\n    at Field.resolve (/restore/scheduling-srv/node_modules/protobufjs/src/field.js:253:94)\n    at Type.set (/restore/scheduling-srv/node_modules/protobufjs/src/type.js:177:38)\n    at Type.get (/restore/scheduling-srv/node_modules/protobufjs/src/type.js:155:45)\n    at Type.create (/restore/scheduling-srv/node_modules/protobufjs/src/type.js:424:20)\n

**Comment by Arun-KumarH** [comment]
Closing.
