### ISSUE TITLE
Pbjs structrues

### ISSUE THREAD

**Issue by Arun-KumarH** [dcodeIO/protobuf.js#847]
protobuf.js version: v6.8

Are protobuf structures not supported in pbjs v6.8 ?
We get below exception during serialization. We did not have this issue in pbjs v6.7.

{ '0': 'Error: .google.protobuf.Value#structValue is not a field: undefined\n    at MessagePrototype.set (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:2490:35)\n    at MessagePrototype.set (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:2483:38)\n    at Message (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:2411:34)\n    at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:1925:28)\n    at new Map (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:4984:46)\n    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:3490:28)\n    at MessagePrototype.set (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:2493:59)\n    at MessagePrototype.set (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:2483:38)\n    at Message (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:2411:34)\n    at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:1925:28)\n    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:3499:33)\n    at MessagePrototype.set (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:2493:59)\n    at MessagePrototype.set (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:2483:38)\n    at Message (/restore/api-resource-srv/node_modules/grpc/node_modules/protobufjs/dist/protobuf.js:2411:34)\n

**Comment by Arun-KumarH** [comment]
Was an issue in my proto and had to keep the snake case. Closing.
