### ISSUE TITLE
reflection with nested message

### ISSUE THREAD

**Issue by angelathewebdev** [dcodeIO/protobuf.js#859]
I've looked through the documentations and APIs, but I couldn't find any example that would describe how to create nested message using the reflection API. An example would be awesome

**Comment by dcodeIO** [comment]
The closest example here is [this one](https://github.com/dcodeIO/protobuf.js#using-reflection-only), but you've probably already seen that.

Basically, you can `.add(...)` a sub-message to anything that's extending `Namespace`.

```js
var AwesomeMessage = new Type("AwesomeMessage").add(new Field("awesomeField", 1, "string"));
var AwesomeSubMessage = new Type("AwesomeSubMessage")...;

AwesomeMessage.add(AwesomeSubMessage);
...
```

**Comment by angelathewebdev** [comment]
What if the nested message is a property of the original message? Where can I denote the property name?

**Comment by dcodeIO** [comment]
The `Type`'s name becomes the property name. Reflection is tightly coupled to its [JSON representation](https://github.com/dcodeIO/protobuf.js#using-json-descriptors).

**Comment by wallaceturner** [comment]
@dcodeIO I think the OP might have been asking about how to add `AwesomeSubMessage` as an actual property of `AwesomeMessage` - your comment `The Type's name becomes the property name` through me off a little as it implies you do not have any flexibility in the naming of complex object fields. 
e.g. in the above example to achieve what i think the OP was actually asking (and i may be mistaken!)

```
AwesomeMessage.add(new Field("subMessage", 2, "AwesomeSubMessage"));
```

**Comment by elderapo** [comment]
I am stuck with the same problem...

I am trying to recreate below example using reflection with no success:
```typescript
import { Field, Message } from "protobufjs";

enum AwesomeEnum {
  ONE = 1,
  TWO = 2
}

class AwesomeSubMessage extends Message {
  @Field.d(1, "string", "required")
  public awesomeString: string;
}

class AwesomeMessage extends Message {
  @Field.d(1, AwesomeSubMessage, "required")
  public awesomeSubMessage: AwesomeSubMessage;

  @Field.d(2, AwesomeEnum, "required")
  public awesomeEnum: AwesomeEnum;
}

const buffer = AwesomeMessage.encode({
  awesomeSubMessage: { awesomeString: "I am an awesome string!" },
  awesomeEnum: AwesomeEnum.TWO
}).finish();

const decoded = AwesomeMessage.decode(buffer);
console.log({ decoded });
```

I thought maybe I could achieve it by writing it like this:
```typescript
import { Field, Type } from "protobufjs";

enum AwesomeEnum {
  ONE = 1,
  TWO = 2
}

const AwesomeSubMessageReflected = new Type("AwesomeSubMessageReflected").add(
  new Field("awesomeString", 1, "string", "required")
);

const AwesomeMessageReflected = new Type("AwesomeMessageReflected")
  .add(
    new Field("awesomeSubMessage", 1, AwesomeSubMessageReflected, "required")
  )
  .add(new Field("awesomeEnum", 2, AwesomeEnum, "required"));

const encoded = AwesomeMessageReflected.encode({
  awesomeSubMessage: { awesomeString: "I am an awesome string!" },
  awesomeEnum: AwesomeEnum.TWO
}).finish();

const decoded = AwesomeMessageReflected.decode(encoded);
console.log({ decoded });
```

But `new Field(...)` is different than `Field.d(...)` and accepts only strings as 3rd arguments so this code doesn't even compile. I thought maybe something like this could work:
```typescript
import { Field, Type } from "protobufjs";

enum AwesomeEnum {
  ONE = 1,
  TWO = 2
}

const AwesomeSubMessageReflected = new Type("AwesomeSubMessageReflected").add(
  new Field("awesomeString", 1, "string", "required")
);

const AwesomeMessageReflected = new Type("AwesomeMessageReflected")
  .add(
    new Field("awesomeSubMessage", 1, "AwesomeSubMessageReflected", "required")
  )
  .add(new Field("awesomeEnum", 2, "AwesomeEnum", "required"));

const encoded = AwesomeMessageReflected.encode({
  awesomeSubMessage: { awesomeString: "I am an awesome string!" },
  awesomeEnum: AwesomeEnum.TWO
}).finish();

const decoded = AwesomeMessageReflected.decode(encoded);
console.log({ decoded });
```
But looks like I need somehow to "globally register" `AwesomeSubMessageReflected` and `AwesomeEnum` so they can be internally resolved by `protobuf.js` because I get following error:
```bash
***********/node_modules/protobufjs/src/namespace.js:410
        throw Error("no such Type or Enum '" + path + "' in " + this);
              ^
Error: no such Type or Enum 'AwesomeSubMessageReflected' in Type AwesomeMessageReflected
    at Type.lookupTypeOrEnum (***********/node_modules/protobufjs/src/namespace.js:410:15)
    at Field.resolve (***********/node_modules/protobufjs/src/field.js:265:94)
    at Type.setup (***********/node_modules/protobufjs/src/type.js:435:41)
    at Type.encode_setup [as encode] (***********/node_modules/protobufjs/src/type.js:485:17)
    at Object.<anonymous> (***********/src/aaa.ts:46:41)
    at Module._compile (module.js:652:30)
    at Module.m._compile (***********/node_modules/ts-node/src/index.ts:413:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (***********/node_modules/ts-node/src/index.ts:416:12)
    at Module.load (module.js:565:32)
error Command failed with exit code 1.
```

**Comment by elderapo** [comment]
Actually I figured it out:
```typescript
import { Field, Type, Enum } from "protobufjs";

enum AwesomeEnum {
  ONE = 1,
  TWO = 2
}

const AwesomeSubMessageReflected = new Type("AwesomeSubMessageReflected").add(
  new Field("awesomeString", 1, "string", "required")
);

const AwesomeMessageReflected = new Type("AwesomeMessageReflected")
  .add(
    new Field("awesomeSubMessage", 1, "AwesomeSubMessageReflected", "required")
  )
  .add(new Field("awesomeEnum", 2, "AwesomeEnum", "required"));

AwesomeMessageReflected.add(new Enum("AwesomeEnum", AwesomeEnum as any)); // <--
AwesomeMessageReflected.add(AwesomeSubMessageReflected); // <--

const encoded = AwesomeMessageReflected.encode({
  awesomeSubMessage: { awesomeString: "I am an awesome string!" },
  awesomeEnum: AwesomeEnum.TWO
}).finish();

const decoded = AwesomeMessageReflected.decode(encoded);
console.log({ decoded });
```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
