### ISSUE TITLE
RangeError - ZMQ + Protobuf

### ISSUE THREAD

**Issue by Oliverr** [dcodeIO/protobuf.js#875]
protobuf.js version: 6.8.0

Running protobuf along side zeromq to subscribe and decode messages from a third party source.
Messages are received fine using ZMQ but using the vendor supplied .proto file returns a `RangeError: index out of range` error

```js
var zmq = require("zmq"),
  sock = zmq.socket('sub');
const protobuf = require('protobufjs');

sock.connect('tcp://10.10.10.113:7779');
sock.subscribe('presence');
console.log('Subscriber connected to port 3000');

sock.on('message', function(topic, message) {
  console.log("--Topic--");
  console.log(topic);
  console.log(topic.toString('utf8'));
  console.log("--Message--");
  console.log(message);
  protobuf.load("schema.proto", function(err, root) {
    if (err)
        throw err;

    var AwesomeMessage = root.lookupType("presence");
    console.log(AwesomeMessage.decode(message));
  });
  console.log("");
});
```

```
<Buffer 08 a9 81 01 10 9a c8 d9 cb 05 18 00 20 88 02 2a 06 00 0c 29 f2 d5 b4 aa 1f 30 10 00 1a 14 99 b5 8b 6a 3c d8 db 0a 75 a0 60 ce 06 79 a1 5f 01 c6 c0 da ... >

/Users/oliver/Documents/Workbench/zmq-test/node_modules/protobufjs/src/reader.js:94
            throw indexOutOfRange(this, 10);
            ^

RangeError: index out of range: 74 + 10 > 74
    at RangeError (native)
    at indexOutOfRange (/Users/oliver/Documents/Workbench/zmq-test/node_modules/protobufjs/src/reader.js:13:12)
    at BufferReader.read_uint32 [as uint32] (/Users/oliver/Documents/Workbench/zmq-test/node_modules/protobufjs/src/reader.js:94:19)
    at Type.mac_address$decode [as decode] (eval at Codegen (/Users/oliver/Documents/Workbench/zmq-test/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:8:11)
    at Type.decode_setup [as decode] (/Users/oliver/Documents/Workbench/zmq-test/node_modules/protobufjs/src/type.js:510:25)
    at Type.presence$decode [as decode] (eval at Codegen (/Users/oliver/Documents/Workbench/zmq-test/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:11:27)
    at Type.decode_setup [as decode] (/Users/oliver/Documents/Workbench/zmq-test/node_modules/protobufjs/src/type.js:510:25)
    at /Users/oliver/Documents/Workbench/zmq-test/app.js:21:32
    at finish (/Users/oliver/Documents/Workbench/zmq-test/node_modules/protobufjs/src/root.js:95:9)
    at process (/Users/oliver/Documents/Workbench/zmq-test/node_modules/protobufjs/src/root.js:123:13)
```

**Comment by Oliverr** [comment]
Doing some more digging, slight modifications to the .proto file results in some output:
```
presence {
  associated: true,
  hashedStaEthMac: <Buffer >,
  apName: '*\u0006\u0000\f)�մ�\u001f0\u0010\u0000\u001a\u0014\u000e\'�����E\r�V\u0007�\u0005!���y_"\fAruba AP 215*\b\n\u0006��\u001e۟\u0000' }
```
Looks like an issue with the .proto?

**Comment by dcodeIO** [comment]
Yeah, might be an issue with the .proto ([see](https://github.com/dcodeIO/protobuf.js/wiki/How-to-reverse-engineer-a-buffer-by-hand)) or a corrupted buffer ([see](https://github.com/dcodeIO/protobuf.js/wiki/How-to-read-binary-data-in-the-browser-or-under-node.js%3F)).

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
