### ISSUE TITLE
decode，error， Illegal offset

### ISSUE THREAD

**Issue by UPBear** [dcodeIO/protobuf.js#886]
protobuf.js version: <5.02>

<please describe the expected and actual behavior>
i make a client connect to a Server for identification,   first ,i send the identification  wire to the Server and the Server decode it succeed ,then  i recieved a wire from Server and decode it  succeed, then i send the second identification wire to Server ,the Server identificated it and return the second wire to me, i decode it with my function same with the first time and get wrong with below message
```js
<please provide a code snippet for reproduction>
```
//original protobuf format
message SecondAuthResp
{  
    required  uint32  result    = 1;
    required  uint32  cliTime   = 2;  
    required  bytes   cliRandno = 3; 
    required  uint32  servTime  = 4;
    required  string  sessionId = 5; 
}

//a function to slice buffer from Server and decode it to expected protobuf message
authFunction.secResqRecieved = function(SecondResqRecievedProto){
       //slice the expected buffer in recieved wire  
	var MsgHeadProtoSliceBuf = SecondResqRecievedProto.slice(0,4);
	var MsgHeadProtoLen = MsgHeadProtoSliceBuf.readIntBE(0,MsgHeadProtoSliceBuf.length);
	var MsgHeadProtoSliceBuf = SecondResqRecievedProto.slice(4,4+MsgHeadProtoLen);
	//decode cipherHead  succeed!!!!
	var MsgHeadProtoBuff = cipherHeader.decode(MsgHeadProtoSliceBuf);
	var MsgAuthProtoCipherSliceBuf = SecondResqRecievedProto.slice(MsgHeadProtoLen + 4, MsgHeadProtoLen + 4 + MsgHeadProtoBuff.payloadLen);	
        //decipher it
   	var decipher = crypto.createDecipheriv('aes-256-cbc', firstRespIns2.key.toBuffer(),firstRespIns2.iv.toBuffer());
   	decipher.setAutoPadding(false);
    var decoded = decipher.update(MsgAuthProtoCipherSliceBuf, 'binary', 'binary');
    decoded += decipher.final('binary');
   	var MsgFirstAuthSliceBuff = new Buffer(decoded,'binary');
    
	//Wrong statement
	var MsgFirstAuthProtoBuff = secondAuthResq.decode(MsgFirstAuthSliceBuff);

	return 0;
}

and  i got:
RangeError: Illegal offset: 0 <= 288 (+1) <= 288
    at RangeError (native)
    at ByteBuffer.module.exports.ByteBufferPrototype.readVarint32 (F:\new_express\node_modules\bytebuffer\dist\bytebuffer-node.js:1540:23)
    at T.ProtoBuf.Reflect.MessagePrototype.decode (F:\new_express\node_modules\protobufjs\dist\protobuf.js:3237:36)
    at Function.Message.decode (F:\new_express\node_modules\protobufjs\dist\protobuf.js:2952:37)
    at Object.exports.secResqRecieved (F:\new_express\nnn.js:49:45)
    at Socket.<anonymous> (F:\new_express\firstSend.js:371:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)

```
<please paste the stack trace of the error if applicable>
```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
