### ISSUE TITLE
Decode a list of messager

### ISSUE THREAD

**Issue by pmosconi** [dcodeIO/protobuf.js#930]
protobuf.js version: 6.8.0

Hi,
I have the following protocol buffer definition that was provided to me:

```js
package proto;

option optimize_for = LITE_RUNTIME;

message Device {
	required string deviceId = 1;
	required int32 signalStrength = 2;
	required DeviceType deviceType = 3;
	optional string uuid = 4;
}

message DevicesFrame {
	required int64 timestamp = 1;
	required int32 frameSize = 2;
	repeated Device devices = 3; 
}

enum DeviceType {
	BT = 0;
	BLE = 1;
    WIFI = 2;
}
```
The buffer I am reading contains several DevicesFrame instances, each one preceded by its lenght and I can read the first one:
```js
  protobuf.load('DevicesFrame.proto', (err, root) => {
    if (err) {
     throw err;
    }
   const DevicesFrame = root.lookupType('proto.DevicesFrame');
   const message = DevicesFrame.decodeDelimited(buf);
   // ...
}
```
I don't know how to skip to the next DevicesFrame and loop through the buffer till the end.

I was given the following sample Python code that loops through the data buffer using the Google protobuffer library,  but I don't know how to do the same thing in node.js (and I'd rather avoid Google's protobuffer implementation because of it's messy installation):

```py
        while n < len(data):
            msg_len, new_pos = _DecodeVarint32(data, n)
            n = new_pos  
            msg_buf = data[n:n+msg_len]
            n += msg_len
            
            message = DevicesFrame.DevicesFrame()
            message.ParseFromString(msg_buf)
```

Thanks in advance for any help and sorry for the seemingly trivial question!

**Comment by dcodeIO** [comment]
Try:

```js
var reader = protobuf.Reader.create(buf);
while (reader.pos < reader.len) {
  var frame = DevicesFrame.decodeDelimited(reader);
  ...
}
```

**Comment by pmosconi** [comment]
[test.zip](https://github.com/dcodeIO/protobuf.js/files/1385638/test.zip)
Thanks a lot. I already tried that but it throws an exception:
```
Error: invalid wire type 6 at offset 17
reader.js:375
    at Error (native)
    at BufferReader.Reader.skipType (c:\xxx\node_modules\protobufjs\src\reader.js:375:19)
    at Type.DevicesFrame$decode [as decode] (eval at Codegen (c:\xxx\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:22:5)
    at Type.decode_setup [as decode] (c:\xxx\node_modules\protobufjs\src\type.js:510:25)
    at Type.decodeDelimited (c:\xxx\node_modules\protobufjs\src\type.js:523:17)
    at module.exports.protobuf.load (c:\xxx\lib\insertTimingsWiFi\index.js:62:36)
    at finish (c:\xxx\node_modules\protobufjs\src\root.js:95:9)
    at process (c:\xxx\node_modules\protobufjs\src\root.js:123:13)
    at c:\xxx\node_modules\protobufjs\src\root.js:182:17
    at fetchReadFileCallback (c:\xxx\node_modules\@protobufjs\fetch\index.js:51:19)
```
Attached is a test file I'm trying to work with.

**Comment by vjpr** [comment]
@dcodeIO

It would be good to have a definitive example in the documentation of how to read from a stream and decode.

I found a few different examples here:

- https://github.com/dcodeIO/protobuf.js/issues/115#issuecomment-73363831
- https://github.com/dcodeIO/protobuf.js/issues/385#issuecomment-170306329

**Comment by kirillgroshkov** [comment]
Spent few hours looking for solution, and here's my working version:

```typescript
function transformFromProtobuf<OUT>(type: protobuf.Type): TransformTyped<Buffer, OUT> {
  let remainder = Buffer.alloc(0)

  return new Transform({
    objectMode: false,
    readableObjectMode: true,
    async transform(chunk: Buffer, _encoding, cb) {
      // console.log(chunk)
      const buf = Buffer.concat([remainder, chunk])

      let lastPos = 0
      const reader = protobuf.Reader.create(buf)
      try {
        while (reader.pos < reader.len) {
          lastPos = reader.pos
          const frame = type.decodeDelimited(reader)
          this.push(frame)
        }

        remainder = Buffer.alloc(0)
      } catch (err) {
        // console.log({pos: reader.pos, lastPos, len: reader.len}, 'got err')
        remainder = buf.slice(lastPos)
      }
      // console.log(`remainder size: ${remainder.length}`)
      cb() // finished processing
    },
  })
}

```

**Comment by ansemjo** [comment]
Not sure if this helps anybody but I landed here as I was trying to decode multiple messages from a [`ReadableStream`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream) inside a [bidirectional WebTransport stream](https://developer.mozilla.org/en-US/docs/Web/API/WebTransportBidirectionalStream).

I used [`alanshaw/it-length-prefixed`](https://github.com/alanshaw/it-length-prefixed/) to decode messages that were written to the wire from Go via `google.golang.org/protobuf/encoding/protodelim` with `pb.MarshalTo(stream, &proto.Message{ ... })` as they luckily both use [VarInts](https://protobuf.dev/programming-guides/encoding/#varints) to encode the chunk length. Here is an incomplete excerpt:

```js
for await (const stream of transport.incomingBidirectionalStreams) {
  // handle each stream in an async IIFE
  (async () => {
    // iterate over varint length-prefixed messages
    for await (const chunk of ItLengthPrefixed.decode(stream.readable)) {
      let message = Message.decode(chunk.subarray());
      console.log(message);
      // ...
    };
  })();
};
```

**Comment by dcodeIO** [comment]
Closing this issue because it has been inactive for more than two years and the project has changed substantially.

If this is still relevant, please open a fresh issue with current reproduction steps, version details, and any updated context.

Please also consider that maintaining protobuf.js takes time and effort. If the project is valuable to you or your organization, sponsorship is appreciated.

Thanks!
