### ISSUE TITLE
"Error: illegal token '3', '=' expected" for reserved field in enum

### ISSUE THREAD

**Issue by ccdunder** [dcodeIO/protobuf.js#949]
protobuf.js version: 6.8.0 and master

Actual: The following proto fails to parse.
Expected: The following proto parses successfully.

``` proto
message Foo {
  enum Status {
    UNKNOWN = 0;
    TRUE = 1;
    FALSE = 2;

    reserved 3;
    reserved "bar";
  }
  ...
}
```

```
Error: illegal token '3', '=' expected (line 7)                                
    at illegal (protobufjs/src/tokenize.js:121:16)
    at skip (protobufjs/src/tokenize.js:292:19)
    at parseEnumValue (protobufjs/src/parse.js:500:9)
    at parseEnum_block (protobufjs/src/parse.js:489:17)
    at ifBlock (protobufjs/src/parse.js:279:17)
    at parseEnum (protobufjs/src/parse.js:484:9)
    at parseCommon (protobufjs/src/parse.js:256:17)
    at parseType_block (protobufjs/src/parse.js:298:17)
    at ifBlock (protobufjs/src/parse.js:279:17)
    at parseType (protobufjs/src/parse.js:297:9) 
```

**Comment by ccdunder** [comment]
Thanks!
