### ISSUE TITLE
util.safeProp is not a function

### ISSUE THREAD

**Issue by viktor-hunko** [dcodeIO/protobuf.js#956]
protobuf.js version: 6.8.1

I'm using proto-webpack-plugin with protobuf.js and after recent updates this error occurs: `util.safeProp is not a function`

proto-webpack-plugin run pbjs like:
```js
pbjs.main(['-t', 'json-module', '-w', 'commonjs', '-o', options.outputFile].concat(files), function(err, output) {
    if (err) { throw err; }
  });
```

```
TypeError: util.safeProp is not a function
    at json_module (/node_modules/proto-webpack-plugin/node_modules/protobufjs/cli/targets/json-module.js:12:29)
    at callTarget (/node_modules/proto-webpack-plugin/node_modules/protobufjs/cli/pbjs.js:296:9)
    at Object.main (/node_modules/proto-webpack-plugin/node_modules/protobufjs/cli/pbjs.js:229:13)
    at new ProtoWebpackPlugin (/node_modules/proto-webpack-plugin/index.js:7:8)
    at Object.<anonymous> (/build/webpack.base.conf.js:77:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

```

**Comment by dcodeIO** [comment]
Does this fix it for you?

**Comment by DenKoren** [comment]
+1 to issue. Commit fixed the problem (at least, no error is thrown after file patching)

**Comment by viktor-hunko** [comment]
@dcodeIO yep, it works. I will be very grateful if you could update npm
Thanks!

**Comment by dcodeIO** [comment]
On npm now as 6.8.3
