### ISSUE TITLE
pbjs dependencies

### ISSUE THREAD

**Issue by djsandb** [dcodeIO/protobuf.js#965]
protobuf.js version: 6.8.3

Trying to use pbjs to generate static js from .proto file. 
`node pbjs -t static ProtoTest.proto > ProtoTest.js`

Error
`Error: Cannot find module '@protobufjs/aspromise'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Admin\Desktop\protobuf.js-master\src\util\minimal.js:5:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)`

**Comment by dcodeIO** [comment]
Might be caused by an old version of npm that doesn't support namespaced modules yet.

**Comment by djsandb** [comment]
I updated npm to 5.6.0 and the issue persists.
