### ISSUE TITLE
Cannot load proto files with dependencies

### ISSUE THREAD

**Issue by n3squik** [dcodeIO/protobuf.js#981]
protobuf.js version: 6.8.4

I cannot load proto files with dependencies. This was working with protobuf.js version 5.0.

- File struct
``` 
- assets/
    |-api/
    |    |-v1/
    |    |    |-messageB.proto
    |    |-messageA.proto
- foo.js
```

- messageA.proto
```
syntax = "proto3";
package com.assets.api;
import "api/v1/messageB.proto";

message MessageA{
    MessageB foo = 0;
}
```

- messageB.proto
```
syntax = "proto3";
package com.assets.api.v1;

message MessageB {
    string bar= 0;
}
```

- with 6.8.4:
```js
var MessageProto = null;
protobuf.load({root:"assets", file:"api/messageA.proto"}, function (err, root) {
    if (root) { MessageAProto = root.lookupType("com.assets.api.MessageA");
}});
data = MessageProto .decode(rawData);
```

```
Error: no such type
    at Root.lookupType (http://localhost:63342/xx/build/app/vendor/protobuf/dist/protobuf.js:3463:15)
    at http://localhost:63342/xx/build/app/src/app/asset/asset.module.js:320:53
    at finish (http://localhost:63342/xx/build/app/vendor/protobuf/dist/protobuf.js:5212:9)
    at Root.load (http://localhost:63342/xx/build/app/vendor/protobuf/dist/protobuf.js:5316:9)
    at Object.load (http://localhost:63342/xx/build/app/vendor/protobuf/dist/protobuf.js:2547:17)
    at new <anonymous> (http://localhost:63342/xx/build/app/src/app/asset/asset.module.js:316:22)
    at Object.instantiate (http://localhost:63342/xx/build/app/vendor/angular/angular.js:4786:14)
    at $controller (http://localhost:63342/xx/build/app/vendor/angular/angular.js:10607:28)
    at Object.<anonymous> (http://localhost:63342/xx/build/app/vendor/angular-ui-router/release/angular-ui-router.js:4081:28)
    at http://localhost:63342/xx/build/app/vendor/angular/angular.js:1259:18
```

- with 5.0:
```js
var MessageProto = null;
dcodeIO.ProtoBuf.convertFieldsToCamelCase = true;
dcodeIO.ProtoBuf.loadProtoFile({root: "assets", file: "api/messageA.proto"}, function (err, builder) {
    if (builder) { MessageProto = builder.build("com.assets.api.MessageA");
}});
data = MessageProto .decode(rawData);
```
```
OK
```

**Comment by dcodeIO** [comment]
> protobuf.load({root:"assets", file:"api/messageA.proto"}

There's no `root` option in 6.x, but you can override [resolvePath](https://github.com/dcodeIO/protobuf.js/blob/master/src/root.js#L62) or use the CLI with `--path`.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!
